### ISSUE TITLE
that means i can not build musca ?

### ISSUE THREAD

**Issue by alavaelian** [enticeing/musca#1]
there is an x in the commint bar

**Comment by enticeing** [comment]
Hey there,

Musca still builds fine, I was able to build a few days ago. 

Are you talking about the red x with a date next to it in the GitHub ui? That’s the GitHub workflows build that I was toying with a while back but never got working. 

Hope this helps.

**Comment by enticeing** [comment]
Reopen this if you want

**Comment by alavaelian** [comment]
there is some screencapture of musca working on or a demostrational video ?
